export const SEARCH_ADDRESS_REQUEST = 'SEARCH_ADDRESS_REQUEST'
export const SEARCH_ADDRESS_SUCCESS = 'SEARCH_ADDRESS_SUCCESS'
export const SEARCH_ADDRESS_FAIL = 'SEARCH_ADDRESS_FAIL'

export const SEARCH_FORECAST_REQUEST = 'SEARCH_FORECAST_REQUEST'
export const SEARCH_FORECAST_SUCCESS = 'SEARCH_FORECAST_SUCCESS'
export const SEARCH_FORECAST_FAIL = 'SEARCH_FORECAST_FAIL'
export const SEARCH_FORECAST_RESET = 'SEARCH_FORECAST_RESET'

export const ADD_FAVORITE = 'ADD_FAVORITE'
