export const SEARCH_ADDRESS_REQUEST = 'SEARCH_ADDRESS_REQUEST'
export const SEARCH_ADDRESS_SUCCESS = 'SEARCH_ADDRESS_SUCCESS'
export const SEARCH_ADDRESS_FAIL = 'SEARCH_ADDRESS_FAIL'

export const SEARCH_WEATHER_REQUEST = 'SEARCH_WEATHER_REQUEST'
export const SEARCH_WEATHER_SUCCESS = 'SEARCH_WEATHER_SUCCESS'
export const SEARCH_WEATHER_FAIL = 'SEARCH_WEATHER_FAIL'
